FROM nginx:1.11

COPY ./infrastructure/nginx.conf /etc/nginx/conf.d/default.conf

COPY web/bundles/ /orbital/web/bundles/
COPY web/css/ /orbital/web/css/
COPY web/fonts/ /orbital/web/fonts/
COPY web/images/ /orbital/web/images/
COPY web/js/ /orbital/web/js/
COPY web/favicon.ico web/robots.txt /orbital/web/
