parameters:
    database_driver: pdo_mysql
    database_host: db
    database_port: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    wkhtmltopdf_path: 'TODO'
